require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListaDeActividadesController do

  # This should return the minimal set of attributes required to create a valid
  # ListaDeActividade. As you add validations to ListaDeActividade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ListaDeActividadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lista_de_actividades as @lista_de_actividades" do
      lista_de_actividade = ListaDeActividade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lista_de_actividades).should eq([lista_de_actividade])
    end
  end

  describe "GET show" do
    it "assigns the requested lista_de_actividade as @lista_de_actividade" do
      lista_de_actividade = ListaDeActividade.create! valid_attributes
      get :show, {:id => lista_de_actividade.to_param}, valid_session
      assigns(:lista_de_actividade).should eq(lista_de_actividade)
    end
  end

  describe "GET new" do
    it "assigns a new lista_de_actividade as @lista_de_actividade" do
      get :new, {}, valid_session
      assigns(:lista_de_actividade).should be_a_new(ListaDeActividade)
    end
  end

  describe "GET edit" do
    it "assigns the requested lista_de_actividade as @lista_de_actividade" do
      lista_de_actividade = ListaDeActividade.create! valid_attributes
      get :edit, {:id => lista_de_actividade.to_param}, valid_session
      assigns(:lista_de_actividade).should eq(lista_de_actividade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListaDeActividade" do
        expect {
          post :create, {:lista_de_actividade => valid_attributes}, valid_session
        }.to change(ListaDeActividade, :count).by(1)
      end

      it "assigns a newly created lista_de_actividade as @lista_de_actividade" do
        post :create, {:lista_de_actividade => valid_attributes}, valid_session
        assigns(:lista_de_actividade).should be_a(ListaDeActividade)
        assigns(:lista_de_actividade).should be_persisted
      end

      it "redirects to the created lista_de_actividade" do
        post :create, {:lista_de_actividade => valid_attributes}, valid_session
        response.should redirect_to(ListaDeActividade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lista_de_actividade as @lista_de_actividade" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListaDeActividade.any_instance.stub(:save).and_return(false)
        post :create, {:lista_de_actividade => { "title" => "invalid value" }}, valid_session
        assigns(:lista_de_actividade).should be_a_new(ListaDeActividade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListaDeActividade.any_instance.stub(:save).and_return(false)
        post :create, {:lista_de_actividade => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lista_de_actividade" do
        lista_de_actividade = ListaDeActividade.create! valid_attributes
        # Assuming there are no other lista_de_actividades in the database, this
        # specifies that the ListaDeActividade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListaDeActividade.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => lista_de_actividade.to_param, :lista_de_actividade => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested lista_de_actividade as @lista_de_actividade" do
        lista_de_actividade = ListaDeActividade.create! valid_attributes
        put :update, {:id => lista_de_actividade.to_param, :lista_de_actividade => valid_attributes}, valid_session
        assigns(:lista_de_actividade).should eq(lista_de_actividade)
      end

      it "redirects to the lista_de_actividade" do
        lista_de_actividade = ListaDeActividade.create! valid_attributes
        put :update, {:id => lista_de_actividade.to_param, :lista_de_actividade => valid_attributes}, valid_session
        response.should redirect_to(lista_de_actividade)
      end
    end

    describe "with invalid params" do
      it "assigns the lista_de_actividade as @lista_de_actividade" do
        lista_de_actividade = ListaDeActividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListaDeActividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => lista_de_actividade.to_param, :lista_de_actividade => { "title" => "invalid value" }}, valid_session
        assigns(:lista_de_actividade).should eq(lista_de_actividade)
      end

      it "re-renders the 'edit' template" do
        lista_de_actividade = ListaDeActividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListaDeActividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => lista_de_actividade.to_param, :lista_de_actividade => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lista_de_actividade" do
      lista_de_actividade = ListaDeActividade.create! valid_attributes
      expect {
        delete :destroy, {:id => lista_de_actividade.to_param}, valid_session
      }.to change(ListaDeActividade, :count).by(-1)
    end

    it "redirects to the lista_de_actividades list" do
      lista_de_actividade = ListaDeActividade.create! valid_attributes
      delete :destroy, {:id => lista_de_actividade.to_param}, valid_session
      response.should redirect_to(lista_de_actividades_url)
    end
  end

end
